server.port=8888
spring.application.name=moyan-server

# 排除数据源自动配置
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Knife4j 配置
knife4j.enable=true
knife4j.setting.language=zh_cn

# JSON 配置
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.default-property-inclusion=non_null

# 日志配置
logging.level.root=INFO
logging.level.com.moyan=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.web.resources.static-locations: classpath:/static/,classpath:/public/
